# Copyright (c) 2025 Kirk Lin
# SPDX-License-Identifier: MIT

from typing import TypedDict, List, Any, Optional


class AgentState(TypedDict):
    """
    Represents the state of the agent workflow.
    """
    # Raw event data from the observer
    raw_events: List[Any]

    # Processed and structured context
    processed_contexts: Optional[List[dict]]

    # A flag to indicate if the event is significant enough to trigger the strategist
    is_significant_event: bool

    # A list of ranked intent candidates generated by the strategist (SkillSpec dicts)
    intent_candidates: Optional[List[dict]]

    # The SkillSpec dict of the currently selected skill (skill / description / params)
    skill_spec: Optional[dict]

    # Human-readable description of the selected task (for display and logging)
    selected_task: Optional[str]

    # Queue of pending SkillSpec dicts approved by the user
    approved_tasks: List[dict]

    # The result of the executed task
    task_result: Any

    # User feedback from the final review
    final_feedback: Optional[str]

    # A list of messages for communication between agents - initialize as empty list
    messages: List[Any]