# Copyright (c) 2025 Kirk Lin
# SPDX-License-Identifier: MIT

from typing import TypedDict, List, Any, Optional


class AgentState(TypedDict):
    """
    Represents the state of the agent workflow.
    """
    # Raw event data from the observer
    raw_events: List[Any]

    # Processed and structured context
    processed_contexts: Optional[List[dict]]

    # A flag to indicate if the event is significant enough to trigger the strategist
    is_significant_event: bool

    # A list of ranked intent candidates generated by the strategist
    intent_candidates: Optional[List[str]]

    # The task selected by the user
    selected_task: Optional[str]

    # A list of all approved tasks
    approved_tasks: List[str]

    # The result of the executed task
    task_result: Any

    # User feedback from the final review
    final_feedback: Optional[str]

    # A list of messages for communication between agents - initialize as empty list
    messages: List[Any]